name: publish-pypi

on: 
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-versions: 3.8
      - name: Install dependencies
        run: |
          pip install -U pip
          pip install poetry
          poetry install
        env:
          POETRY_VIRTUALENVS_CREATE: true
      - name: Build
        run: |
          poetry build
      - name: publish
        run: |
          poetry publish --repository pypi